name: Build Keenetic MIPSLE Softfloat

on:
  workflow_dispatch: # Позволяет запускать сборку вручную кнопкой
  release:
    types: [published]

jobs:
  build-keenetic:
    runs-on: ubuntu-latest
    container: rust:1.70.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cross-compiler
        run: apt-get update && apt-get install -y gcc-mipsel-linux-gnu

      - name: Add mipsel target
        run: rustup target add mipsel-unknown-linux-gnu

      - name: Build for MIPS LE
        run: |
          cargo update
          CARGO_TARGET_MIPSEL_UNKNOWN_LINUX_GNU_LINKER=mipsel-linux-gnu-gcc cargo build --release --target mipsel-unknown-linux-gnu

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shadow-tls-keenetic-mipsel-softfloat
          path: target/mipsel-unknown-linux-gnu/release/shadow-tls
