name: Build Keenetic MIPSLE Softfloat

on:
  workflow_dispatch: # Позволяет запускать сборку вручную кнопкой
  release:
    types: [published]

jobs:
  build-keenetic:
    runs-on: ubuntu-latest
    container: messense/rust-musl-cross:mipsel-musl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build for MIPS LE musl
        run: |
          cargo update -p ring
          cargo build --release --target mipsel-unknown-linux-musl

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shadow-tls-keenetic-mipsel-softfloat
          path: target/mipsel-unknown-linux-musl/release/shadow-tls
